name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action to do
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - run: echo "🍏 This job's status is ${{ job.status }}."   
      - run: echo "Hello Ayodele the coder"
      - run: docker version
